config/routes.rb
Rails.application.routes.draw do

  get "sessions/new"
  root "static_pages#home"
  get  "/help", to: "static_pages#help"
  get  "/about", to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  delete "/logout", to: "sessions#destroy"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  resources :users
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def self.digest string
    if cost = ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = t "account_activated"
      redirect_to user
    else
      flash[:danger] = t "invalid_active"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == "1" ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = t "account_not_activated"
        message += t "check_active"
        flash[:warning] = message
        redirect_to root_url
      end

    else
      flash.now[:danger] = t "invalid"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :find_user, excpet: [:new, :index, :user_params,
    :logged_in_user, :admin_user]
  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = t "pls_check_mail"
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t "deleted"
    redirect_to users_url
  end

  def edit; end

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = t "profile_update"
      redirect_to @user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user)
    .permit :name, :email, :password, :password_confirmation
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t "please_login"
      redirect_to login_url
    end
  end

  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def find_user
    @user = User.find_by id :params[:id]
    return if @user
    flash[:danger] = t "please_login"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = flash[:notice] = t("base_title'")
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    user == current_user
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget user
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="<%= t "tutorial_link" %> "><%= t "tutorial" %></a>
    by <a href="<%= t "name_link" %>"><%= t "name" %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to ( t "about" ) , about_path %></li>
      <li><%= link_to ( t "contact" ), contact_path %></li>
      <li><a href="<%= t "new_tutorial_link" %> ">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to ( t "sample_app"), "#", id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to (t "home"), root_path %></li>
            <li><%= link_to (t "help"), help_path %></li>
            <% if logged_in? %>
              <li><%= link_to (t "user"), users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t "account" %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to (t "profile"), current_user %></li>
                  <li><%= link_to (t "setting"), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t("login"), logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to t("login"), login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all",
                                              "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
     <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if User.new.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form" %> <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% User.new.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1><%= t ".title" %></h1>
<p>
  The <a href="https://www.railstutorial.org/"><em><%= t ".desc_sample" %></em>
  </a> is a
  <a href="https://www.railstutorial.org/book"><%= t "book" %></a> and
  <a href="http://screencasts.railstutorial.org/"><%= t "series" %></a>
  <%= t ".desc" %>
  <a href="http://rubyonrails.org/"><%= t "ror" %></a>.
  <%= t "desc_sample" %>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1><%= t ".title" %></h1>
<p>
  <%= t ".desc" %>
  <a href="https://www.railstutorial.org/contact"><%= t ".page" %></a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1><%= t ".title" %></h1>
<p>
 <%= t ".get_help" %> <%= t "tutorial" %> at the
  <a href="https://www.railstutorial.org/help"><%= t ".rails" %> help section</a>
  . <%= t ".to_help" %>
  <a href="https://www.railstutorial.org/book"><em><%= t ".tutorial" %></em>
  <%= t "book" %></a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>

  <h2>
    <%= t ".desc" %>
    <a href="https://www.railstutorial.org/"><%= t "tutorial" %></a>
    <%= t "sample" %>
  </h2>

  <%= link_to ( t "signup"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            "http://rubyonrails.org/" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= render "shared/error_messages", object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit ( t ".button"), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: t "you_sure" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,( t "base_title") %>
<h1><%= t".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t "change" %> </a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1><%= t ".title"%></h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
   <%= render @users %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1><%= t ".title"%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>